# Generated by Django 3.0.6 on 2021-06-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ur',
            name='old',
            field=models.TextField(max_length=200),
        ),
    ]
